services:
  service_product_management:
    build: .
    image: service_product_management
    container_name: service_product_management
    hostname: product_management
    ports:
      - "8000:8000"
    volumes:
      - "./app:/services/app"
    restart: "on-failure"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/health-check"]
      interval: 1m30s
      timeout: 2s
      retries: 3
    networks:
      - dbnet
    depends_on:
      - postgres
      - postgres_test

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    env_file: ".env"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dbnet

  postgres_test:
    image: postgres:17-alpine
    container_name: postgres_test
    env_file: ".test.env"
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
    networks:
      - dbnet

  adminer:
    image: adminer:standalone
    container_name: adminer
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - "postgres_test:db_test"
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres
      - postgres_test

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data-test:
  postgres-data: