services:
  service_product_management:
    build: .
    image: service_product_management
    container_name: service_product_management
    hostname: product_management
    ports:
      - "8000:8000"
    volumes:
      - ".:/services"
    restart: "on-failure"
    healthcheck:
      test: curl -f http://0.0.0.0:8000/health-check || exit 1
      interval: 1m30s
      timeout: 2s
      retries: 3
    links:
      - "postgres:db_host"
      - "postgres_test:db_host_test"
      - "rabbitmq_products:rmq_host"
      - "redis_products:redis_host"
    networks:
      - dbnet
    depends_on:
      - postgres
      - postgres_test
      - rabbitmq_products
      - redis_products

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    env_file:
      - ".env"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dbnet

  postgres_test:
    image: postgres:17-alpine
    container_name: postgres_test
    env_file:
      - ".test.env"
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
    networks:
      - dbnet

  adminer:
    image: adminer:standalone
    container_name: adminer
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - "postgres_test:db_test"
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres
      - postgres_test

  rabbitmq_products:
    image: rabbitmq:3.12-management-alpine
    hostname: rabbitmq_products
    container_name: rabbitmq_products
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER:${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS:${RMQ_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - dbnet

  redis_products:
    image: redis:latest
    hostname: redis_products
    container_name: redis_products
    ports:
      - "6381:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    networks:
      - dbnet

  kraken:
    build:
      context: ./getaway
      dockerfile: Dockerfile
    image: kraken
    container_name: kraken
    ports:
      - "8085:8085"
    networks:
      - dbnet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data-test:
  postgres-data:
  rabbitmq-data:
  redis-data: